# Generated by Django 4.0.4 on 2023-03-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_alter_previouswork_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='previouswork',
            name='img_url',
        ),
        migrations.AddField(
            model_name='previouswork',
            name='img',
            field=models.ImageField(null=True, upload_to='staticfiles/assets/images/work'),
        ),
    ]
